### ISSUE TITLE
Maybe could remove '#' before module name for common import usage

### ISSUE THREAD

**Issue by AdvancedCat** [xitu/inline-module#2]
I konw the first character ‘#’ in module name is to declare that module from a inline-module script with id attribute.
But I feel a little awkward when importing module with '#'. In my sense, 'foo' is module, not '#foo', like this:
```js
import { bar } from 'foo'
```
In case of module conflict, maybe can store two names in importmap, one is 'foo', another is '#foo', unless has other better choices.

**Comment by akira-cn** [comment]
~~Deprecated~~

> Add `prefix` attribute to give other choices, prefix is `#` by default(**recommend**).
> 
> Now you can use:
> 
> ```html
> <script src="https://unpkg.com/inline-module/index.js" setup prefix=""></script>
> ```
> 
> to remove `#`. 
> 
> Or
> 
> ```html
> <script src="https://unpkg.com/inline-module/index.js" setup noprefix></script>
> ```
> 
> as shortcut.
>

**Comment by AdvancedCat** [comment]
LGTM

**Comment by akira-cn** [comment]
> LGTM

Maybe `name` attribute is a better way.

Now:

```html
  <script type="inline-module" name="foo" id="bar">
  const foo = 'bar';
  export default foo;
  </script>
```

Either `import foo from 'foo'` or `import foo from '#bar'` is Okey.
